id: P009323
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD97
  title: ཆབ་ཤོག་ཕྱོགས་བསྒྲིག་
  author: ''
  volumes:
    6ae010891c9a4940a80122720c46e231:
      image_group_id: I1PD466
      title: ''
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
