id: I74A547D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:22:03+00:00'
last_modified: '2022-06-08T10:12:11.696013+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD97
  title: ཆབ་ཤོག་ཕྱོགས་བསྒྲིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F5A1:
      image_group_id: I1PD466
      title: ''
      total_pages: 240
      order: 1
      base_file: F5A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
